/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['.wrap_youtube_player[_ngcontent-%COMP%]{ position:absolute; z-index:100 }\r\n.btn_player-close[_ngcontent-%COMP%]{ position:absolute; width:25px; height:25px; background:#fff; opacity:0.3; z-index:100;}'];
//# sourceMappingURL=player.component.css.shim.ngstyle.js.map