/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/youtube/youtube.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from './youtube.component.css.shim.ngstyle';
import * as import10 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import11 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import12 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '../../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import16 from '@angular/core/src/change_detection/change_detection_util';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/router/src/router_outlet_map';
import * as import21 from '@angular/core/src/linker/component_factory_resolver';
import * as import22 from '@angular/forms/src/directives/default_value_accessor';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/common/src/directives/ng_for';
import * as import28 from '@angular/router/src/directives/router_outlet';
import * as import29 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import30 from '../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import31 from '@angular/core/src/linker/query_list';
import * as import32 from '../../../node_modules/@angular/common/src/directives/ng_style.ngfactory';
import * as import33 from '@angular/router/src/router_state';
import * as import34 from '@angular/common/src/location/location_strategy';
import * as import35 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import36 from '@angular/common/src/directives/ng_style';
import * as import37 from '@angular/router/src/directives/router_link';
import * as import38 from '@angular/router/src/directives/router_link_active';
export class Wrapper_YoutubeComponent {
  /*private*/ _eventHandler:Function;
  context:import0.YoutubeComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.YoutubeComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    if ((eventName == 'window:googleApiClientReady')) {
      const pd_sub_0:any = ((<any>this.context.ngOnInit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_YoutubeComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_YoutubeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.YoutubeComponent>;
  _YoutubeComponent_0_3:Wrapper_YoutubeComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_YoutubeComponent_Host0,renderType_YoutubeComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_YoutubeComponent0(this.viewUtils,this,0,this._el_0);
    this._YoutubeComponent_0_3 = new Wrapper_YoutubeComponent(this.compView_0.ref,this.injectorGet(import8.Router,this.parentIndex));
    this.compView_0.create(this._YoutubeComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'googleApiClientReady','window'),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._YoutubeComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.YoutubeComponent) && (0 === requestNodeIndex))) { return this._YoutubeComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._YoutubeComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._YoutubeComponent_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
export const YoutubeComponentNgFactory:import7.ComponentFactory<import0.YoutubeComponent> = new import7.ComponentFactory<import0.YoutubeComponent>('ng-component',View_YoutubeComponent_Host0,import0.YoutubeComponent);
const styles_YoutubeComponent:any[] = [import9.styles];
var renderType_YoutubeComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_YoutubeComponent,{});
export class View_YoutubeComponent0 extends import1.AppView<import0.YoutubeComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _DefaultValueAccessor_18_3:import10.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_18_4:any[];
  _NgModel_18_5:import11.Wrapper_NgModel;
  _NgControl_18_6:any;
  _NgControlStatus_18_7:import12.Wrapper_NgControlStatus;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _el_105:any;
  _text_106:any;
  _anchor_107:any;
  /*private*/ _vc_107:import13.ViewContainer;
  _TemplateRef_107_5:any;
  _NgFor_107_6:import14.Wrapper_NgFor;
  _text_108:any;
  _text_109:any;
  _text_110:any;
  _el_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _text_117:any;
  _text_118:any;
  _text_119:any;
  _text_120:any;
  _el_121:any;
  _text_122:any;
  _el_123:any;
  _text_124:any;
  _el_125:any;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _text_133:any;
  _el_134:any;
  _text_135:any;
  _text_136:any;
  _text_137:any;
  _text_138:any;
  _el_139:any;
  /*private*/ _vc_139:import13.ViewContainer;
  _RouterOutlet_139_5:import15.Wrapper_RouterOutlet;
  /*private*/ _expr_150:any;
  /*private*/ _expr_151:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_YoutubeComponent0,renderType_YoutubeComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_150 = import16.UNINITIALIZED;
    this._expr_151 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','mdl-layout mdl-js-layout mdl-layout--fixed-header'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','nav_youtube mdl-layout__header '),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray8(8,'aria-expanded','false','class','mdl-layout__drawer-button','role','button','tabindex','0'),(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'i',new import3.InlineArray2(2,'class','material-icons'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right mdl-textfield--full-width'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'label',new import3.InlineArray4(4,'class','mdl-button mdl-js-button mdl-button--icon','for','search-field'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'i',new import3.InlineArray2(2,'class','material-icons'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'search',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','mdl-textfield__expandable-holder'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'input',new import3.InlineArray8(6,'class','mdl-textfield__input inp_search','id','search-field','type','text'),(null as any));
    this._DefaultValueAccessor_18_3 = new import10.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_18));
    this._NG_VALUE_ACCESSOR_18_4 = [this._DefaultValueAccessor_18_3.context];
    this._NgModel_18_5 = new import11.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_18_4);
    this._NgControl_18_6 = this._NgModel_18_5.context;
    this._NgControlStatus_18_7 = new import12.Wrapper_NgControlStatus(this._NgControl_18_6);
    this._text_19 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','mdl-layout__drawer'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'nav',new import3.InlineArray2(2,'class','mdl-navigation'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','logo_gman'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'i',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'g',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_27,'i',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'m',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_27,'i',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'a',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_27,'i',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'n',(null as any));
    this._text_37 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._text_38 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_25,'div',new import3.InlineArray2(2,'class','sort_description'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n                ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'span',new import3.InlineArray2(2,'class','txt'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._text_44 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray2(2,'class','mdl-navigation__link'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'i',new import3.InlineArray4(4,'class','mdl-color-text--blue-grey-400 material-icons','role','presentation'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'people',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_45,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'ViewCount',(null as any));
    this._text_52 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._text_53 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray2(2,'class','mdl-navigation__link'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n                ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'i',new import3.InlineArray4(4,'class','mdl-color-text--blue-grey-400 material-icons','role','presentation'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'stars',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n                ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_54,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'Rating',(null as any));
    this._text_61 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._text_62 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray2(2,'class','mdl-navigation__link'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n                ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'i',new import3.InlineArray4(4,'class','mdl-color-text--blue-grey-400 material-icons','role','presentation'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'playlist_add_check',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n                ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_63,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Relevance',(null as any));
    this._text_70 = this.renderer.createText(this._el_63,'\n            ',(null as any));
    this._text_71 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray2(2,'class','mdl-navigation__link'),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n                ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_72,'i',new import3.InlineArray4(4,'class','mdl-color-text--blue-grey-400 material-icons','role','presentation'),(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'date_range',(null as any));
    this._text_76 = this.renderer.createText(this._el_72,'\n                ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_72,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'Date',(null as any));
    this._text_79 = this.renderer.createText(this._el_72,'\n            ',(null as any));
    this._text_80 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_81 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray2(2,'class','mdl-navigation__link'),(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'\n                ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_81,'i',new import3.InlineArray4(4,'class','mdl-color-text--blue-grey-400 material-icons','role','presentation'),(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'movie',(null as any));
    this._text_85 = this.renderer.createText(this._el_81,'\n                ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_81,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'VideoCount',(null as any));
    this._text_88 = this.renderer.createText(this._el_81,'\n            ',(null as any));
    this._text_89 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray2(2,'class','mdl-navigation__link'),(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'\n                ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_90,'i',new import3.InlineArray4(4,'class','mdl-color-text--blue-grey-400 material-icons','role','presentation'),(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'subtitles',(null as any));
    this._text_94 = this.renderer.createText(this._el_90,'\n                ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_90,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'Title',(null as any));
    this._text_97 = this.renderer.createText(this._el_90,'\n            ',(null as any));
    this._text_98 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_99 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_100 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','mdl-layout__content'),(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'\n        ',(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_101,'div',new import3.InlineArray2(2,'class','ct_youtube'),(null as any));
    this._text_104 = this.renderer.createText(this._el_103,'\n            ',(null as any));
    this._el_105 = import3.createRenderElement(this.renderer,this._el_103,'ul',new import3.InlineArray2(2,'class','list_video'),(null as any));
    this._text_106 = this.renderer.createText(this._el_105,'\n                ',(null as any));
    this._anchor_107 = this.renderer.createTemplateAnchor(this._el_105,(null as any));
    this._vc_107 = new import13.ViewContainer(107,105,this,this._anchor_107);
    this._TemplateRef_107_5 = new import18.TemplateRef_(this,107,this._anchor_107);
    this._NgFor_107_6 = new import14.Wrapper_NgFor(this._vc_107.vcRef,this._TemplateRef_107_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_108 = this.renderer.createText(this._el_105,'\n            ',(null as any));
    this._text_109 = this.renderer.createText(this._el_103,'\n        ',(null as any));
    this._text_110 = this.renderer.createText(this._el_101,'\n        ',(null as any));
    this._el_111 = import3.createRenderElement(this.renderer,this._el_101,'div',new import3.InlineArray2(2,'class','mdl-typography--text-center'),(null as any));
    this._text_112 = this.renderer.createText(this._el_111,'\n            ',(null as any));
    this._el_113 = import3.createRenderElement(this.renderer,this._el_111,'button',new import3.InlineArray2(2,'class','btn_more_content mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect'),(null as any));
    this._text_114 = this.renderer.createText(this._el_113,'\n                ',(null as any));
    this._el_115 = import3.createRenderElement(this.renderer,this._el_113,'i',new import3.InlineArray2(2,'class','material-icons'),(null as any));
    this._text_116 = this.renderer.createText(this._el_115,'add',(null as any));
    this._text_117 = this.renderer.createText(this._el_113,'\n            ',(null as any));
    this._text_118 = this.renderer.createText(this._el_111,'\n        ',(null as any));
    this._text_119 = this.renderer.createText(this._el_101,'\n    ',(null as any));
    this._text_120 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_121 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','video_loading'),(null as any));
    this._text_122 = this.renderer.createText(this._el_121,'\n        ',(null as any));
    this._el_123 = import3.createRenderElement(this.renderer,this._el_121,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_124 = this.renderer.createText(this._el_123,'\n            ',(null as any));
    this._el_125 = import3.createRenderElement(this.renderer,this._el_123,'div',new import3.InlineArray2(2,'class','c1'),(null as any));
    this._text_126 = this.renderer.createText(this._el_123,'\n            ',(null as any));
    this._el_127 = import3.createRenderElement(this.renderer,this._el_123,'div',new import3.InlineArray2(2,'class','c2'),(null as any));
    this._text_128 = this.renderer.createText(this._el_123,'\n            ',(null as any));
    this._el_129 = import3.createRenderElement(this.renderer,this._el_123,'div',new import3.InlineArray2(2,'class','c3'),(null as any));
    this._text_130 = this.renderer.createText(this._el_123,'\n            ',(null as any));
    this._el_131 = import3.createRenderElement(this.renderer,this._el_123,'div',new import3.InlineArray2(2,'class','c4'),(null as any));
    this._text_132 = this.renderer.createText(this._el_123,'\n        ',(null as any));
    this._text_133 = this.renderer.createText(this._el_121,'\n        ',(null as any));
    this._el_134 = import3.createRenderElement(this.renderer,this._el_121,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_135 = this.renderer.createText(this._el_134,'loading',(null as any));
    this._text_136 = this.renderer.createText(this._el_121,'\n    ',(null as any));
    this._text_137 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_138 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_139 = import3.createRenderElement(this.renderer,parentRenderNode,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_139 = new import13.ViewContainer(139,(null as any),this,this._el_139);
    this._RouterOutlet_139_5 = new import15.Wrapper_RouterOutlet(this.parentView.injectorGet(import20.RouterOutletMap,this.parentIndex),this._vc_139.vcRef,this.parentView.injectorGet(import21.ComponentFactoryResolver,this.parentIndex),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_10));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray8(8,'ngModelChange',(null as any),'keypress',(null as any),'blur',(null as any),'input',(null as any)),this.eventHandler(this.handleEvent_18));
    this._NgModel_18_5.subscribe(this,this.eventHandler(this.handleEvent_18),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_45,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_45));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_54,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_54));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_63,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_63));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_72,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_72));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_81,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_81));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_90,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_90));
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_113,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_113));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._el_105,
      this._text_106,
      this._anchor_107,
      this._text_108,
      this._text_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._text_118,
      this._text_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._text_136,
      this._text_137,
      this._text_138,
      this._el_139
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.DefaultValueAccessor) && (18 === requestNodeIndex))) { return this._DefaultValueAccessor_18_3.context; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (18 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_18_4; }
    if (((token === import24.NgModel) && (18 === requestNodeIndex))) { return this._NgModel_18_5.context; }
    if (((token === import25.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_6; }
    if (((token === import26.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_7.context; }
    if (((token === import18.TemplateRef) && (107 === requestNodeIndex))) { return this._TemplateRef_107_5; }
    if (((token === import27.NgFor) && (107 === requestNodeIndex))) { return this._NgFor_107_6.context; }
    if (((token === import28.RouterOutlet) && (139 === requestNodeIndex))) { return this._RouterOutlet_139_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_18_1_0:any = this.context.query;
    this._NgModel_18_5.check_model(currVal_18_1_0,throwOnChange,false);
    this._NgModel_18_5.ngDoCheck(this,this._el_18,throwOnChange);
    this._NgControlStatus_18_7.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_107_0_0:any = this.context.videos;
    this._NgFor_107_6.check_ngForOf(currVal_107_0_0,throwOnChange,false);
    this._NgFor_107_6.ngDoCheck(this,this._anchor_107,throwOnChange);
    this._RouterOutlet_139_5.ngDoCheck(this,this._el_139,throwOnChange);
    this._vc_107.detectChangesInNestedViews(throwOnChange);
    this._vc_139.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatus_18_7.checkHost(this,this,this._el_18,throwOnChange);
    const currVal_150:any = import3.inlineInterpolate(1,'Sort by ',this.context.order,'');
    if (import3.checkBinding(throwOnChange,this._expr_150,currVal_150)) {
      this.renderer.setText(this._text_42,currVal_150);
      this._expr_150 = currVal_150;
    }
    const currVal_151:boolean = !this.context.isLoading;
    if (import3.checkBinding(throwOnChange,this._expr_151,currVal_151)) {
      this.renderer.setElementProperty(this._el_121,'hidden',currVal_151);
      this._expr_151 = currVal_151;
    }
  }
  destroyInternal():void {
    this._vc_107.destroyNestedViews();
    this._vc_139.destroyNestedViews();
    this._NgModel_18_5.ngOnDestroy();
    this._RouterOutlet_139_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 107)) { return new View_YoutubeComponent1(this.viewUtils,this,107,this._anchor_107,this._vc_107); }
    return (null as any);
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onSearch($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_18_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.query = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'keypress')) {
      const pd_sub_1:any = ((<any>this.context.onSearch($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'blur')) {
      const pd_sub_2:any = ((<any>this.context.onSearch($event)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
  handleEvent_45(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickedSort('viewCount')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_54(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickedSort('rating')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_63(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickedSort('relevance')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_72(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickedSort('date')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_81(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickedSort('videoCount')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_90(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickedSort('title')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_113(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onLoadMoreContent()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_YoutubeComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import29.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_2_4:import30.Wrapper_RouterLinkActive;
  _query_RouterLink_2_0:import31.QueryList<any>;
  _query_RouterLinkWithHref_2_1:import31.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _NgStyle_4_3:import32.Wrapper_NgStyle;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _map_21:any;
  /*private*/ _expr_22:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_YoutubeComponent1,renderType_YoutubeComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_21 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {'background-image': p0};
    });
    this._expr_22 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'class','video_item show'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_2_3 = new import29.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import8.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import33.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import34.LocationStrategy,this.parentView.parentIndex));
    this._RouterLinkActive_2_4 = new import30.Wrapper_RouterLinkActive(this.parentView.parentView.injectorGet(import8.Router,this.parentView.parentIndex),new import17.ElementRef(this._el_2),this.renderer);
    this._query_RouterLink_2_0 = new import31.QueryList<any>();
    this._query_RouterLinkWithHref_2_1 = new import31.QueryList<any>();
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','bg_video'),(null as any));
    this._NgStyle_4_3 = new import32.Wrapper_NgStyle(this.parentView.parentView.injectorGet(import35.KeyValueDiffers,this.parentView.parentIndex),new import17.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_4,'\n                            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','description'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'span',new import3.InlineArray2(2,'class','ellipsis'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','bg_description'),(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n                            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.NgStyle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgStyle_4_3.context; }
    if (((token === import37.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLinkWithHref_2_3.context; }
    if (((token === import38.RouterLinkActive) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLinkActive_2_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = import3.inlineInterpolate(1,'./player/',this.context.$implicit.id.videoId,'');
    this._RouterLinkWithHref_2_3.check_routerLink(currVal_2_0_0,throwOnChange,false);
    this._RouterLinkWithHref_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_1_0:any = 'active';
    this._RouterLinkActive_2_4.check_routerLinkActive(currVal_2_1_0,throwOnChange,false);
    this._RouterLinkActive_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_4_0_0:any = this._map_21((('url(' + this.context.$implicit.snippet.thumbnails.high.url) + ')'));
    this._NgStyle_4_3.check_ngStyle(currVal_4_0_0,throwOnChange,false);
    this._NgStyle_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_2_0.dirty) {
        this._query_RouterLink_2_0.reset(([] as any[]));
        this._RouterLinkActive_2_4.context.links = this._query_RouterLink_2_0;
        this._query_RouterLink_2_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_2_1.dirty) {
        this._query_RouterLinkWithHref_2_1.reset([this._RouterLinkWithHref_2_3.context]);
        this._RouterLinkActive_2_4.context.linksWithHrefs = this._query_RouterLinkWithHref_2_1;
        this._query_RouterLinkWithHref_2_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_2_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_2_3.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_22:any = import3.inlineInterpolate(1,'',this.context.$implicit.snippet.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setText(this._text_9,currVal_22);
      this._expr_22 = currVal_22;
    }
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.ngOnDestroy();
    this._RouterLinkActive_2_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
}